[env]
TERM = "xterm-256color"

[font]
size = 11

[font.normal]
family = "Maple Mono"
style = "bold"

[window.padding]
x = 5

[general]
import = [
  "~/.config/alacritty/catppuccin-macchiato.toml"
]



